apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-grafana
  namespace: default
  labels:
    app: custom-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-grafana
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: custom-grafana
    spec:
      restartPolicy: Always
      containers:
      - name: custom-grafana
        image: winds6206/custom-grafana:9.5.14
        ports:
          - containerPort: 3000
        env:
          - name: TZ
            value: Asia/Taipei
          - name: GF_SERVER_HTTP_PORT
            value: "3000"
      securityContext:
        fsGroup: 472
        runAsUser: 472
